//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientServiceVolApp.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vol", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Vol : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime DepartureDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestinationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VolNumberField;
        
        private System.DateTime DepartureTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime DepartureDate {
            get {
                return this.DepartureDateField;
            }
            set {
                if ((this.DepartureDateField.Equals(value) != true)) {
                    this.DepartureDateField = value;
                    this.RaisePropertyChanged("DepartureDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Destination {
            get {
                return this.DestinationField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinationField, value) != true)) {
                    this.DestinationField = value;
                    this.RaisePropertyChanged("Destination");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string VolNumber {
            get {
                return this.VolNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.VolNumberField, value) != true)) {
                    this.VolNumberField = value;
                    this.RaisePropertyChanged("VolNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime DepartureTime {
            get {
                return this.DepartureTimeField;
            }
            set {
                if ((this.DepartureTimeField.Equals(value) != true)) {
                    this.DepartureTimeField = value;
                    this.RaisePropertyChanged("DepartureTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Comments {
            get {
                return this.CommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentsField, value) != true)) {
                    this.CommentsField = value;
                    this.RaisePropertyChanged("Comments");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément destination de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetVols", ReplyAction="*")]
        ClientServiceVolApp.ServiceReference1.GetVolsResponse GetVols(ClientServiceVolApp.ServiceReference1.GetVolsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetVols", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientServiceVolApp.ServiceReference1.GetVolsResponse> GetVolsAsync(ClientServiceVolApp.ServiceReference1.GetVolsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVolsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVols", Namespace="http://tempuri.org/", Order=0)]
        public ClientServiceVolApp.ServiceReference1.GetVolsRequestBody Body;
        
        public GetVolsRequest() {
        }
        
        public GetVolsRequest(ClientServiceVolApp.ServiceReference1.GetVolsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetVolsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime departureDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string destination;
        
        public GetVolsRequestBody() {
        }
        
        public GetVolsRequestBody(System.DateTime departureDate, string destination) {
            this.departureDate = departureDate;
            this.destination = destination;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVolsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVolsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientServiceVolApp.ServiceReference1.GetVolsResponseBody Body;
        
        public GetVolsResponse() {
        }
        
        public GetVolsResponse(ClientServiceVolApp.ServiceReference1.GetVolsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetVolsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientServiceVolApp.ServiceReference1.Vol[] GetVolsResult;
        
        public GetVolsResponseBody() {
        }
        
        public GetVolsResponseBody(ClientServiceVolApp.ServiceReference1.Vol[] GetVolsResult) {
            this.GetVolsResult = GetVolsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ClientServiceVolApp.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ClientServiceVolApp.ServiceReference1.WebService1Soap>, ClientServiceVolApp.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientServiceVolApp.ServiceReference1.GetVolsResponse ClientServiceVolApp.ServiceReference1.WebService1Soap.GetVols(ClientServiceVolApp.ServiceReference1.GetVolsRequest request) {
            return base.Channel.GetVols(request);
        }
        
        public ClientServiceVolApp.ServiceReference1.Vol[] GetVols(System.DateTime departureDate, string destination) {
            ClientServiceVolApp.ServiceReference1.GetVolsRequest inValue = new ClientServiceVolApp.ServiceReference1.GetVolsRequest();
            inValue.Body = new ClientServiceVolApp.ServiceReference1.GetVolsRequestBody();
            inValue.Body.departureDate = departureDate;
            inValue.Body.destination = destination;
            ClientServiceVolApp.ServiceReference1.GetVolsResponse retVal = ((ClientServiceVolApp.ServiceReference1.WebService1Soap)(this)).GetVols(inValue);
            return retVal.Body.GetVolsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientServiceVolApp.ServiceReference1.GetVolsResponse> ClientServiceVolApp.ServiceReference1.WebService1Soap.GetVolsAsync(ClientServiceVolApp.ServiceReference1.GetVolsRequest request) {
            return base.Channel.GetVolsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientServiceVolApp.ServiceReference1.GetVolsResponse> GetVolsAsync(System.DateTime departureDate, string destination) {
            ClientServiceVolApp.ServiceReference1.GetVolsRequest inValue = new ClientServiceVolApp.ServiceReference1.GetVolsRequest();
            inValue.Body = new ClientServiceVolApp.ServiceReference1.GetVolsRequestBody();
            inValue.Body.departureDate = departureDate;
            inValue.Body.destination = destination;
            return ((ClientServiceVolApp.ServiceReference1.WebService1Soap)(this)).GetVolsAsync(inValue);
        }
    }
}
